# Generated by Django 6.0.1 on 2026-02-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del modelo (ej: YZF-R1)', max_length=200, verbose_name='Nombre')),
                ('categoria', models.CharField(choices=[('sport', 'Sport'), ('touring', 'Touring'), ('naked', 'Naked'), ('adventure', 'Adventure'), ('scooter', 'Scooter')], default='sport', max_length=20, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en USD', max_digits=10, verbose_name='Precio')),
                ('cilindrada', models.IntegerField(help_text='Capacidad del motor en centímetros cúbicos', verbose_name='Cilindrada (cc)')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la moto', verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motos/', verbose_name='Imagen')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['categoria'], name='motos_moto_categor_3cfd0d_idx'), models.Index(fields=['disponible'], name='motos_moto_disponi_c46f3b_idx')],
            },
        ),
    ]
